### ISSUE TITLE
Korektura blogpostu Tester 1.4.0

### ISSUE THREAD

**Issue by milo** [nette/proofreading#10]
Našel by se někdo, kdo by udělal korekturu https://github.com/nette/proofreading/commit/5b9792791f1a6860da0f81a0e7495ffb2f77af02? Lezlo to ze mě jak z chlupaté deky. @phusar ?

**Comment by phusar** [comment]
Cau, pozriem na to zajtra po praci.

**Comment by milo** [comment]
Publikováno
