### ISSUE TITLE
Korekce blogpostu

### ISSUE THREAD

**Issue by milo** [nette/proofreading#7]
Prosím o korekci kraťoučkého blogpostu: https://github.com/nette/proofreading/blob/master/blog-tester-phar-duality.texy

//cc @phusar

**Comment by milo** [comment]
Publikováno http://blog.nette.org/changes-in-nette-tester-1-5-0

**Comment by phusar** [comment]
Cau, buduci vikend by som mal mat cas, a chcel by som prejst vsetky
publikovane clanky. Si otvoreny myslienke dodatocnych korekcii?

2015-07-24 12:42 GMT+02:00 Miloslav Hůla <notifications@github.com>:

**Comment by milo** [comment]
Jasně. Když zůstane zachován obsah tak jak je, velmi rád korekturu přijmu.
